name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gamja-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Env
        uses: xom9ikk/dotenv@v2.3.0

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: gamja
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository_owner }}/gamja:${{ env.GAMJA_REF }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            KIMCHI_REF=${{ env.KIMCHI_REF }}
            GAMJA_REF=${{ env.GAMJA_REF }}

  soju-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Env
        uses: xom9ikk/dotenv@v2.3.0

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: soju
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository_owner }}/soju:${{ env.SOJU_REF }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SOJU_REF=${{ env.SOJU_REF }}
